/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./hooks/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // AI Decoder Academy design system (from Stitch)
        "background": "#0e0e13",
        "surface": "#0e0e13",
        "surface-dim": "#0e0e13",
        "surface-container-lowest": "#000000",
        "surface-container-low": "#131319",
        "surface-container": "#19191f",
        "surface-container-high": "#1f1f26",
        "surface-container-highest": "#25252d",
        "surface-bright": "#2c2b33",
        "surface-variant": "#25252d",
        "on-surface": "#f9f5fd",
        "on-surface-variant": "#acaab1",
        "on-background": "#f9f5fd",
        "primary": "#a1faff",
        "primary-container": "#00f4fe",
        "primary-dim": "#00e5ee",
        "primary-fixed": "#00f4fe",
        "primary-fixed-dim": "#00e5ee",
        "on-primary": "#006165",
        "on-primary-container": "#00575b",
        "on-primary-fixed": "#004346",
        "on-primary-fixed-variant": "#006266",
        "secondary": "#d873ff",
        "secondary-container": "#9900ce",
        "secondary-dim": "#bc00fb",
        "secondary-fixed": "#f1c1ff",
        "secondary-fixed-dim": "#ebadff",
        "on-secondary": "#39004f",
        "on-secondary-container": "#fff5fc",
        "on-secondary-fixed": "#580078",
        "on-secondary-fixed-variant": "#8400b2",
        "tertiary": "#9dfaff",
        "tertiary-container": "#72eff5",
        "tertiary-fixed": "#72eff5",
        "tertiary-fixed-dim": "#63e1e7",
        "tertiary-dim": "#63e1e7",
        "on-tertiary": "#006164",
        "on-tertiary-container": "#00585b",
        "on-tertiary-fixed": "#004346",
        "on-tertiary-fixed-variant": "#006266",
        "outline": "#76747b",
        "outline-variant": "#48474d",
        "error": "#ff716c",
        "error-container": "#9f0519",
        "error-dim": "#d7383b",
        "on-error": "#490006",
        "on-error-container": "#ffa8a3",
        "inverse-surface": "#fcf8ff",
        "inverse-primary": "#006a6e",
        "inverse-on-surface": "#55545b",
        "surface-tint": "#a1faff",
      },
      fontFamily: {
        headline: ["Space Grotesk", "system-ui", "sans-serif"],
        body: ["Manrope", "system-ui", "sans-serif"],
        label: ["Space Grotesk", "system-ui", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      animation: {
        "fade-in": "fadeIn 0.5s ease-in-out",
        "slide-up": "slideUp 0.4s ease-out",
        "pulse-height": "pulseHeight 1.2s ease-in-out infinite",
        "scan": "scan 2s linear infinite",
      },
      keyframes: {
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        slideUp: {
          "0%": { transform: "translateY(20px)", opacity: "0" },
          "100%": { transform: "translateY(0)", opacity: "1" },
        },
        pulseHeight: {
          "0%, 100%": { height: "4px" },
          "50%": { height: "24px" },
        },
        scan: {
          "0%": { transform: "translateY(-100%)" },
          "100%": { transform: "translateY(100vh)" },
        },
      },
    },
  },
  plugins: [],
};
